### ISSUE TITLE
Python3 port

### ISSUE THREAD

**Issue by skrzepto** [fedora-infra/fmn.sse#25]
This should be easy to port, might not need any modifications

**Comment by atelic** [comment]
`python setup.py install` fails on Python 3.5.1:

```
running install
running bdist_egg
running egg_info
writing namespace_packages to fmn.sse.egg-info/namespace_packages.txt
writing dependency_links to fmn.sse.egg-info/dependency_links.txt
writing fmn.sse.egg-info/PKG-INFO
writing top-level names to fmn.sse.egg-info/top_level.txt
writing requirements to fmn.sse.egg-info/requires.txt
reading manifest file 'fmn.sse.egg-info/SOURCES.txt'
writing manifest file 'fmn.sse.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
warning: build_py: byte-compiling is disabled, skipping.

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/fmn
creating build/bdist.linux-x86_64/egg/fmn/sse
copying build/lib/fmn/sse/subscriber.py -> build/bdist.linux-x86_64/egg/fmn/sse
copying build/lib/fmn/sse/__init__.py -> build/bdist.linux-x86_64/egg/fmn/sse
copying build/lib/fmn/sse/FeedQueue.py -> build/bdist.linux-x86_64/egg/fmn/sse
copying build/lib/fmn/sse/sse_webserver.py -> build/bdist.linux-x86_64/egg/fmn/sse
copying build/lib/fmn/__init__.py -> build/bdist.linux-x86_64/egg/fmn
warning: install_lib: byte-compiling is disabled, skipping.

creating build/bdist.linux-x86_64/egg/EGG-INFO
copying fmn.sse.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fmn.sse.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fmn.sse.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fmn.sse.egg-info/namespace_packages.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fmn.sse.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fmn.sse.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fmn.sse.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/fmn.sse-0.1.0-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing fmn.sse-0.1.0-py3.5.egg
removing '/home/ebarbour/.virtualenvs/py3sse/lib/python3.5/site-packages/fmn.sse-0.1.0-py3.5.egg' (and everything under it)
creating /home/ebarbour/.virtualenvs/py3sse/lib/python3.5/site-packages/fmn.sse-0.1.0-py3.5.egg
Extracting fmn.sse-0.1.0-py3.5.egg to /home/ebarbour/.virtualenvs/py3sse/lib/python3.5/site-packages
warning: easy_install: byte-compiling is disabled, skipping.

fmn.sse 0.1.0 is already the active version in easy-install.pth

Installed /home/ebarbour/.virtualenvs/py3sse/lib/python3.5/site-packages/fmn.sse-0.1.0-py3.5.egg
Processing dependencies for fmn.sse==0.1.0
Searching for cryptography
Reading https://pypi.python.org/simple/cryptography/
Downloading https://pypi.python.org/packages/a9/5b/a383b3a778609fe8177bd51307b5ebeee369b353550675353f46cb99c6f0/cryptography-1.4.tar.gz#md5=a9763e3831cc7cdb402c028fac1ceb39
Best match: cryptography 1.4
Processing cryptography-1.4.tar.gz
Writing /tmp/ebarbour/easy_install-37oooiih/cryptography-1.4/setup.cfg
Running cryptography-1.4/setup.py -q bdist_egg --dist-dir /tmp/ebarbour/easy_install-37oooiih/cryptography-1.4/egg-dist-tmp-jbujbppp
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*' found under directory 'vectors'
warning: build_py: byte-compiling is disabled, skipping.

build/temp.linux-x86_64-3.5/_openssl.c:2:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
```

**Comment by atelic** [comment]
`sudo dnf install python3-devel` fixes this

**Comment by skrzepto** [comment]
We will need to add that into the readme then.

**Comment by skrzepto** [comment]
I get
```
raise TypeError("HTTP response status message must be bytes")
```

I might need to append a `b''` to the status codes and headers

**Comment by atelic** [comment]
Running the `sse_webserver.py` and opening a connection gives:

```
Unhandled Error
Traceback (most recent call last):
  File "/home/ebarbour/.virtualenvs/py3sse/lib/python3.5/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/home/ebarbour/.virtualenvs/py3sse/lib/python3.5/site-packages/twisted/web/http.py", line 1692, in lineReceived
    self.allContentReceived()
  File "/home/ebarbour/.virtualenvs/py3sse/lib/python3.5/site-packages/twisted/web/http.py", line 1781, in allContentReceived
    req.requestReceived(command, path, version)
  File "/home/ebarbour/.virtualenvs/py3sse/lib/python3.5/site-packages/twisted/web/http.py", line 768, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/home/ebarbour/.virtualenvs/py3sse/lib/python3.5/site-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/home/ebarbour/.virtualenvs/py3sse/lib/python3.5/site-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/home/ebarbour/.virtualenvs/py3sse/lib/python3.5/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "fmn/sse/sse_webserver.py", line 42, in render_GET
    reason="Invalid Path")
  File "fmn/sse/sse_webserver.py", line 81, in invalid_request
    request.setResponseCode(code, reason)
  File "/home/ebarbour/.virtualenvs/py3sse/lib/python3.5/site-packages/twisted/web/http.py", line 1063, in setResponseCode
    raise TypeError("HTTP response status message must be bytes")
builtins.TypeError: HTTP response status message must be bytes


```

**Comment by skrzepto** [comment]
lets hold off on the port until issue #1 is resolved

**Comment by skrzepto** [comment]
checkout `py3-port` branch for work. just needs tests to be fixed

**Comment by skrzepto** [comment]
This has been completed
